### ISSUE TITLE
Unhandled exception when using the advanced compiler

### ISSUE THREAD

**Issue by Hachem-H** [WeihanLi/dotnet-exec#1]
![image](https://user-images.githubusercontent.com/83752039/178965744-dda8e932-c4e2-4db2-8cc0-9696761623be.png)

I am running a basic script containing nothing but a `Console.WriteLine`, the program works fine using the default compiler, but as soon as I run it using the advanced compiler, it breaks and gives me an unhandled exception. So is the case with using `-a`.

**Comment by WeihanLi** [comment]
Thanks for the feedback, the advanced mode is not working because of the issue <https://github.com/dotnet/roslyn/issues/61454>

and the issue you met with is can not find the project file, it would look for the project file within the same directory, and you can specify the project file with the `--project` option.

The advanced mode is to analyze the project file to get the package references and global usings for compiling, currently had to use the default compiler, sorry for the inconvenience

**Comment by hh-Naram** [comment]
Ah I see thanks for the response, I don't think I was running this script through a project which is probably why it broke. In either way I was just pretty curious on how what the advanced compiler worked so I blindly plugged it in.

**Comment by WeihanLi** [comment]
Never mind, thanks for the feedback, removed the compiler type from readme for now

**Comment by WeihanLi** [comment]
Removed the advanced compiler, so I'm going to close this
